version: 0.0
os: linux
files:
  - source: /pplTest
    destination: /var/
hooks:
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy/app_stop.sh
      timeout: 300
      runas: root
