version: 0.0
os: linux
files:
  - source: /
    destination: /usr/sample-ppl
file_exists_behavior: OVERWRITE
permission:
  - object: /usr/sample-ppl
    pattern: ""
    owner: ec2-user
    model: 777
    type:
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root