version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/nodejs
hooks:
  BeforeInstall:
   - location: scripts/install_app_dependencies.sh
     timeout: 500
     runas: ubuntu
  ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 300
     runas: ubuntu